# Step 1: Build the React app
FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy all source files into the container
COPY . .

# Build the React application
RUN npm run build

# Step 2: Serve with NGINX
FROM nginx:stable-alpine as production

# Copy the build folder from the build stage to the NGINX container
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
