# Use the official Node.js image as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all the project files to the container
COPY . .

# Expose port 8000 for the backend
EXPOSE 8000

# Command to start the Node.js app
CMD ["node", "index.js"]
